### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by LuanTeles** [DropSonic0/Flash-Player-PS3-Store#2]
Hey DropSonic0 :)

Nice work with Mario Boom! I've been enjoying it.

I want to ask if I can add your flash games to my [repo](https://github.com/PS3-4K-Pro/Flash). I've been delaying adding more games for years XD. Can I add yours?

**Comment by DropSonic0** [comment]
> Hey DropSonic0 :)
> 
> Nice work with Mario Boom! I've been enjoying it.
> 
> I want to ask if I can add your flash games to my [repo](https://github.com/PS3-4K-Pro/Flash). I've been delaying adding more games for years XD. Can I add yours?

of course no problem

**Comment by LuanTeles** [comment]
Thank you :)
